name: Enforce Branch Source Rules

on:
  pull_request:
    branches:
      - production
      - main

permissions:
  contents: read
  pull-requests: read
  statuses: write
  checks: write

jobs:
  check-branch-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch policy
        run: |
          BASE_BRANCH="${{ github.base_ref }}"  # target branch of the PR
          HEAD_BRANCH="${{ github.head_ref }}"  # source branch of the PR

          echo "PR from $HEAD_BRANCH into $BASE_BRANCH"

          # Rule 1: Only dev or main → production
          if [ "$BASE_BRANCH" = "production" ] && [ "$HEAD_BRANCH" != "dev" ] && [ "$HEAD_BRANCH" != "main" ]; then
            echo "❌ Only dev or main can merge into production."
            echo "Current source: $HEAD_BRANCH"
            echo "Allowed sources for production: dev, main"
            exit 1
          fi

          # Rule 2: Only production → main
          if [ "$BASE_BRANCH" = "main" ] && [ "$HEAD_BRANCH" != "production" ]; then
            echo "❌ Only production can merge into main."
            echo "Current source: $HEAD_BRANCH"
            echo "Allowed source for main: production"
            exit 1
          fi

          echo "✅ Branch policy check passed!"
