name: Enforce Branch Source Rules

on:
  pull_request:
    branches:
      - production
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch policy
        run: |
          BASE_BRANCH="${{ github.base_ref }}"  # target branch of the PR
          HEAD_BRANCH="${{ github.head_ref }}"  # source branch of the PR

          echo "PR from $HEAD_BRANCH into $BASE_BRANCH"

          # Rule 1: Only dev or main → production
          if [ "$BASE_BRANCH" = "production" ] && [ "$HEAD_BRANCH" != "dev" ] && [ "$HEAD_BRANCH" != "main" ]; then
            echo "❌ Only dev or main can merge into production."
            exit 1
          fi

          # Rule 2: Only production → main
          if [ "$BASE_BRANCH" = "main" ] && [ "$HEAD_BRANCH" != "production" ]; then
            echo "❌ Only production can merge into main."
            exit 1
          fi
